# finally in try except

finally block can be included along with try except block when a perticular block of code is to be executed regardless of an error or not in try block

try:
  print(x)
except:
  print("Something went wrong")
finally:
  print("I would always get executed")
  
  
[Click here for DYI](https://colab.research.google.com/github/pythoncoder100/practice/blob/master/finally_try_except.ipynb)
